version: '3.7'
services:    
    app:
       build: .
       command: npm start       
       ports: 
         - '3000:3000'
       volumes: 
         - .:/usr/app

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        volumes:
            - /home/fulpi/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    